language: java
notifications:
  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
deploy:
  provider: heroku
  api_key:
    secure: Olti+9H8VpQZnog7tVeNNnNGQTRNDyegg8W1s7VttKtsnRUHpCYLZdGkVP/b0mNej8g6LhIHNix0MZB1OjZCUoQs6cEZ6eO2UFPZQqO3dqt1EeRDpMiqqCgfKgPKZiKCFQzkd4ZJzy7b58/NhkW12zJCUuudgJwHiSinM0bOqYQwpAcu5AOM4JSG0RkboD66JtHu2P4/TXyFBuoWVu3oPzV4jKOXt4od1yJy8QhuZqf7YgGoSeFzUmhGcZbkRel7fDhfVXLQFLV+K6bXht7x7oS4HEdKp4QeKyMkSEsHR6FEogW8xSnN98/v4nZziP0JRhhDwSBNfVZiYvBSZgwSRf26bh6TRlMd69WI5h0RttWLPVEj0TqReyzxHTBfrvPTfF12ztbKcyLyiVBGmiC9BsT4R4eoIBHXT6pd/Hmd/1W6c8iL0z4wY90W1k5kwdKLRcj2Xx4VoDjSGfd1+y0eFI6/4iJrkPVuhxpiN3u4cyiCbYKTcUodmR3ic92p/ziRs7rJy8Af+ml2oU/H49NKoL1at3vymz1ewlHFS7gX7gdnj24vi5jFqs6BMOXy5BiWT8qked0F8JcFSh3SDwfXu610mQbXqQRh22/kYLLwY5ihVur6Y4EFlNEWvOGNetkUY1S2RJMC8wxZUXVeWQ9V7oSOAD4dAgYc3/N9BrgRVmU=
